import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const SettingsContext = createContext();

const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    activeSession: 'Session active',
    logout: 'Déconnexion',
    theme: 'Thème',
    light: 'Clair',
    dark: 'Sombre',
    language: 'Langue',
    user: 'Utilisateur',
    email: 'Email',
    password: 'Mot de passe',
    login: 'Se connecter',
    loginError: 'Email ou mot de passe incorrect',
    loginSuccess: 'Connexion réussie',
    logoutSuccess: 'Déconnecté',
    crm: 'CRM',
    accounts: 'Comptes',
    contacts: 'Contacts',
    reports: 'Rapports',
    sales: 'Ventes',
    quotes: 'Devis',
    proforma: 'Factures proforma',
    orders: 'Commandes',
    deliveryNotes: 'Bons de livraison',
    invoices: 'Factures',
    creditNotes: 'Avoirs',
    recurringInvoices: 'Factures récurrentes',
    purchases: 'Achats',
    priceRequests: 'Demandes des prix',
    purchaseOrders: 'Bons de commandes',
    receptions: 'Bons de réception',
    finance: 'Finance',
    transactions: 'Transactions',
    collection: 'Recouvrement',
    reconciliation: 'Rapprochement',
    bankStatements: 'Relevés bancaires',
    chequeDeposits: 'Remises de chèques',
    cheques: 'Chèques',
    catalog: 'Catalogue',
    articles: 'Articles',
    collaborators: 'Collaborateurs',
    users: 'Utilisateurs',
    history: 'Historique',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    activeSession: 'جلسة نشطة',
    logout: 'تسجيل الخروج',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    language: 'اللغة',
    user: 'المستخدم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    login: 'دخول',
    loginError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    loginSuccess: 'تم تسجيل الدخول',
    logoutSuccess: 'تم تسجيل الخروج',
    crm: 'العلاقات',
    accounts: 'الحسابات',
    contacts: 'جهات الاتصال',
    reports: 'التقارير',
    sales: 'المبيعات',
    quotes: 'العروض',
    proforma: 'فاتورة أولية',
    orders: 'الطلبات',
    deliveryNotes: 'أذونات التسليم',
    invoices: 'الفواتير',
    creditNotes: 'الإشعارات الدائنة',
    recurringInvoices: 'الفواتير المتكررة',
    purchases: 'المشتريات',
    priceRequests: 'طلبات الأسعار',
    purchaseOrders: 'طلبات الشراء',
    receptions: 'الاستلام',
    finance: 'المالية',
    transactions: 'المعاملات',
    collection: 'التحصيل',
    reconciliation: 'المطابقة',
    bankStatements: 'كشوفات البنك',
    chequeDeposits: 'إيداع الشيكات',
    cheques: 'الشيكات',
    catalog: 'الكتالوج',
    articles: 'المواد',
    collaborators: 'الموظفون',
    users: 'المستخدمون',
    history: 'السجل',
  },
  en: {
    dashboard: 'Dashboard',
    activeSession: 'Active session',
    logout: 'Logout',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    language: 'Language',
    user: 'User',
    email: 'Email',
    password: 'Password',
    login: 'Sign in',
    loginError: 'Invalid email or password',
    loginSuccess: 'Signed in',
    logoutSuccess: 'Signed out',
    crm: 'CRM',
    accounts: 'Accounts',
    contacts: 'Contacts',
    reports: 'Reports',
    sales: 'Sales',
    quotes: 'Quotes',
    proforma: 'Proforma invoices',
    orders: 'Orders',
    deliveryNotes: 'Delivery notes',
    invoices: 'Invoices',
    creditNotes: 'Credit notes',
    recurringInvoices: 'Recurring invoices',
    purchases: 'Purchases',
    priceRequests: 'Price requests',
    purchaseOrders: 'Purchase orders',
    receptions: 'Receptions',
    finance: 'Finance',
    transactions: 'Transactions',
    collection: 'Collection',
    reconciliation: 'Reconciliation',
    bankStatements: 'Bank statements',
    chequeDeposits: 'Cheque deposits',
    cheques: 'Cheques',
    catalog: 'Catalog',
    articles: 'Articles',
    collaborators: 'Collaborators',
    users: 'Users',
    history: 'History',
  },
};

export const SettingsProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'fr');

  useEffect(() => {
    localStorage.removeItem('theme');
    document.documentElement.classList.remove('dark');
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      dir: language === 'ar' ? 'rtl' : 'ltr',
      t: translations[language] || translations.fr,
    }),
    [language],
  );

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>;
};

export const useSettings = () => useContext(SettingsContext);
